<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exhibit: Case {{ $case->reference_number }}</title>
    <style>
        /* --- Page Setup --- */
        @page {
            margin: 0.75in;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 11pt;
            color: #333;
            line-height: 1.4;   
        }

        /* --- Repeating Header & Footer --- */
        #header { position: fixed; top: -0.6in; left: 0; right: 0; }
        #footer { position: fixed; bottom: -0.6in; left: 0; right: 0; text-align: center; font-size: 9pt; color: #777; }
        #footer .page-number:after { content: counter(page); }

        /* --- Content Styling --- */
        .header-table, .summary-table { width: 100%; border-collapse: collapse; }
        .header-table td, .summary-table td { vertical-align: top; padding: 2px; }
        .logo { width: 60px; height: auto; font-weight: bold; }
        
        h1 { text-align: center; font-size: 22pt; font-weight: bold; color: #000; text-transform: uppercase; letter-spacing: 3px; border: 2px solid #000; padding: 10px; margin: 15px 0; }
        h2 { font-size: 13pt; font-weight: bold; color: #000; text-transform: uppercase; border-bottom: 1px solid #333; padding-bottom: 5px; margin-top: 25px; margin-bottom: 10px; }
        
        .qr-code { width: 140px; height: 140px; }
        
        .details-box {
            border: 1px solid #ccc;
            padding: 10px;
            min-height: 140px;
        }
        
        .gallery-item {
            border: 1px solid #ccc;
            padding: 15px;
            margin-bottom: 20px;
            page-break-inside: avoid;
        }
        .gallery-item img {
            width: 100%;
            height: 300px;
            display: block;
            margin-bottom: 10px;
        }
        .caption {
            font-size: 11pt;
            text-align: left;
        }
        .caption p {
            margin: 4px 0;
        }
        .caption strong {
            font-weight: bold;
        }
        
        .video-placeholder {
            border: 2px dashed #ccc;
            padding: 40px 10px;
            text-align: center;
            margin-bottom: 10px;
        }
        .video-link {
            font-size: 9pt;
            color: #0000EE;
            text-decoration: underline;
            word-wrap: break-word;
        }
    </style>
</head>
<body>

    <div id="header">
        <table class="header-table">
            <tr>
                <td> <img src="{{ asset('images/logo.jpg') }}" alt="Police Badge" class="logo"></td>
                <td style="text-align: right;">
                    <strong>Station:</strong> {{ $case->station->name }}<br>
                    <strong>CID </strong> {{ $case->scene_reference_number }}
                </td>
            </tr>
        </table>
    </div>

    <div id="footer">
        Generated by CID Studios on {{ now()->format('d M Y, H:i:s') }} | Page <span class="page-number"></span>
    </div>

    <main>
        <h1>Exhibit</h1>
        <h2>Case Summary</h2>

        <table class="summary-table">
            <tr>
                {{-- Left Column: Details --}}
                <td style="width: 50%; padding-right: 15px;">
                    <div class="details-box">
                        <strong>Brief Circumstances:</strong>
                        <p style="white-space: pre-line; font-size: 10pt;">{{ $case->circumstances }}</p>
                    </div>
                </td>
                {{-- Right Column: QR Code --}}
                <td style="width: 50%; padding-left: 15px;">
                    <img src="{{ $qrCode }}" alt="Case QR Code" class="qr-code">
                </td>
            </tr>
        </table>

        <h2>Photographic & Video Evidence</h2>

        @if($mediaItems->isEmpty())
            <p>No media files were attached to this case.</p>
        @else
            @php
                function toAlpha($num){ return chr(substr("00".($num-1),-2,2)+65); }
                $exhibitCounter = 1;
            @endphp
            @foreach($mediaItems as $media)
                <div class="gallery-item">
                    @if($media->type === 'image')
                        <img src="{{ public_path('storage/' . $media->path) }}" alt="Exhibit Image">
                    @else
                        <div class="video-placeholder">
                            <p><strong>[Video Evidence]</strong></p>
                            <a href="{{ Storage::disk('public')->url($media->path) }}" class="video-link">
                                Link: {{ $case->scene_reference_number }}_Exhibit_{{ toAlpha($exhibitCounter) }}.mp4
                            </a>
                        </div>
                    @endif
                    <div class="caption">
                        <p><strong>Exhibit {{ toAlpha($exhibitCounter) }}</strong></p>
                        <p><strong>Description:</strong> {{ $media->description ?? 'No description provided.' }}</p>
                        <p><strong>Captured At:</strong> {{ $media->created_at->format('d M Y, H:i:s') }}</p>
                    </div>
                </div>
                @php $exhibitCounter++; @endphp
            @endforeach
        @endif
    </main>

</body>
</html>